# Docker compose file for testing.

version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    container_name: bank-dg0.1
    working_dir: /data/dg0.1
    ports:
      - 5080:5080
      - 6080:6080
    labels:
      cluster: test
      service: zero
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero -o 0 --my=zero1:5080 --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10

  dg1:
    image: dgraph/dgraph:latest
    container_name: bank-dg1
    working_dir: /data/dg1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
    ports:
      - 8180:8180
      - 9180:9180
    labels:
      cluster: test
      service: alpha
    command: /gobin/dgraph alpha --my=dg1:7180 --lru_mb=1024 --zero=zero1:5080 -o 100 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16  --acl_secret_file /dgraph-acl/hmac-secret --enterprise_features --acl_access_ttl 10s

  dg2:
    image: dgraph/dgraph:latest
    container_name: bank-dg2
    working_dir: /data/dg2
    depends_on:
      - dg1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
    ports:
      - 8182:8182
      - 9182:9182
    labels:
      cluster: test
      service: alpha
    command: /gobin/dgraph alpha --my=dg2:7182 --lru_mb=1024 --zero=zero1:5080 -o 102 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 --acl_secret_file /dgraph-acl/hmac-secret --enterprise_features --acl_access_ttl 10s

  dg3:
    image: dgraph/dgraph:latest
    container_name: bank-dg3
    working_dir: /data/dg3
    depends_on:
      - dg2
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
    ports:
      - 8183:8183
      - 9183:9183
    labels:
      cluster: test
      service: alpha
    command: /gobin/dgraph alpha --my=dg3:7183 --lru_mb=1024 --zero=zero1:5080 -o 103 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 --acl_secret_file /dgraph-acl/hmac-secret --enterprise_features --acl_access_ttl 10s
